services:
  redis:
    image: redis:alpine
    container_name: receipt_processor-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  receipt_processor:
    container_name: receipt_processor-api
    build: .
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - redis
