database:
  path: "receipt_processor.db" # We could probably change this to call a db that's remote

server:
  port: "8080"

redis:
  addr: "redis:6379" # This is ok for a small scale, but if want to scale, it would be better to use remote redis instead
  username: ""
  password: ""
  db: 0
